# Generated by Django 2.2.7 on 2019-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '帖子分类表', 'verbose_name_plural': '帖子分类表'},
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=128, verbose_name='帖子标题'),
        ),
    ]
