# Generated by Django 2.2.7 on 2019-12-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191206_2245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('name', 'is_active')},
        ),
    ]
