# Generated by Django 2.2.7 on 2019-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191207_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='praise_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='收藏数量'),
        ),
    ]
