# Generated by Django 2.2.7 on 2019-12-13 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20191208_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '帖子表', 'verbose_name_plural': '帖子表'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('content', models.TextField(verbose_name='评论')),
                ('praise_num', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('author_id', models.IntegerField(db_index=True, verbose_name='创建人')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='post.PostReply', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '帖子评论表',
                'verbose_name_plural': '帖子评论表',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
