# Generated by Django 2.2.7 on 2019-12-16 17:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20191213_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='not_reply',
            field=models.BooleanField(default=True, verbose_name='是否可以回复'),
        ),
        migrations.AddField(
            model_name='postreply',
            name='post_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='帖子id'),
        ),
        migrations.AddField(
            model_name='postreply',
            name='replier_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='回复人id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='post.Category', verbose_name='父亲ID'),
        ),
    ]
