# Generated by Django 2.2.7 on 2019-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20191216_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='post_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='帖子id'),
            preserve_default=False,
        ),
    ]
