# Generated by Django 2.2.7 on 2020-05-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200426_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_time',), 'verbose_name': '帖子表', 'verbose_name_plural': '帖子表'},
        ),
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(default=123, verbose_name='html帖子内容'),
            preserve_default=False,
        ),
    ]
