# Generated by Django 2.2.7 on 2020-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200523_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '文章'), (2, '问题')], default=1, verbose_name='文章类型'),
        ),
    ]
