# Generated by Django 2.2.7 on 2020-06-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200524_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(null=True, verbose_name='帖子封面'),
        ),
    ]
