# Generated by Django 2.2.7 on 2020-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='newest_num',
            field=models.IntegerField(default=None, verbose_name='最新回复人'),
            preserve_default=False,
        ),
    ]
