# Generated by Django 2.2.7 on 2020-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20200710_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='newest_num',
        ),
        migrations.AddField(
            model_name='post',
            name='newest_id',
            field=models.IntegerField(null=True, verbose_name='最新回复人'),
        ),
    ]
