# Generated by Django 2.2.7 on 2020-07-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20200710_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='newest_id',
            new_name='newest_user_id',
        ),
    ]
