# Generated by Django 2.2.7 on 2020-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20200710_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(max_length=512, null=True, verbose_name='帖子简介'),
        ),
    ]
