# Generated by Django 2.2.14 on 2020-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(default='', max_length=512, verbose_name='帖子简介'),
        ),
    ]
