# Generated by Django 2.2.14 on 2020-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20200722_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_time',), 'verbose_name': '文章/问题表', 'verbose_name_plural': '文章/问题表'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '上线'), (1, '用户删除'), (2, '管理员删除'), (3, '点赞数过低删除'), (4, '内容违规')], default=0, verbose_name='文章上下线状态'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('status', 'name')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
