# Generated by Django 2.2.14 on 2020-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreply',
            options={'ordering': ('-created_time', 'praise_num'), 'verbose_name': '帖子评论表', 'verbose_name_plural': '帖子评论表'},
        ),
        migrations.AddField(
            model_name='postreply',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
            preserve_default=False,
        ),
    ]
