# Generated by Django 2.2.14 on 2020-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20200929_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='is_read',
            field=models.BooleanField(null=True, verbose_name='是否已读'),
        ),
    ]
