# Generated by Django 2.2.14 on 2020-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_auto_20200929_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreply',
            name='html_content',
            field=models.TextField(default='', verbose_name='评论'),
            preserve_default=False,
        ),
    ]
