# Generated by Django 2.2.14 on 2020-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_postreply_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newest_time',
            field=models.DateTimeField(null=True, verbose_name='回复时间'),
        ),
    ]
