# Generated by Django 2.2.14 on 2020-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_newest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='排序'),
        ),
    ]
