# Generated by Django 2.2.14 on 2020-09-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_category_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
