# Generated by Django 2.2.14 on 2020-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_auto_20200930_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=32, verbose_name='关键字')),
            ],
            options={
                'verbose_name': '敏感词过滤表',
                'verbose_name_plural': '敏感词过滤表',
            },
        ),
    ]
