# Generated by Django 2.2.7 on 2019-11-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('is_email', models.BooleanField(default=False, verbose_name='邮箱认证')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=2, verbose_name='性别')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像')),
                ('is_phone', models.BooleanField(default=False, verbose_name='手机认证')),
                ('birth', models.DateField(default=None, verbose_name='生日')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
