# Generated by Django 2.2.7 on 2019-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191203_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymity',
            field=models.BooleanField(default=False, verbose_name='匿名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
