# Generated by Django 2.2.7 on 2019-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191206_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=None, null=True, verbose_name='生日'),
        ),
    ]
