# Generated by Django 2.2.7 on 2019-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191206_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_num',
            field=models.IntegerField(default=0, verbose_name='登录次数'),
        ),
    ]
