# Generated by Django 2.2.7 on 2020-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200403_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=100, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
