# Generated by Django 2.2.7 on 2020-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200404_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brief',
            field=models.CharField(max_length=200, null=True, verbose_name='个人简介'),
        ),
    ]
