# Generated by Django 2.2.14 on 2020-07-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_addr',
            field=models.CharField(default='', max_length=64, verbose_name='上次登录地点'),
        ),
    ]
