# Generated by Django 2.2.7 on 2020-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('user_id', models.IntegerField(verbose_name='创建人')),
                ('url', models.URLField(verbose_name='上传地址')),
            ],
            options={
                'verbose_name': '上传文件历史表',
                'verbose_name_plural': '上传文件历史表',
            },
        ),
    ]
