# Generated by Django 2.2.7 on 2020-05-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20200414_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadhistorymodel',
            options={'ordering': ('-created_time',), 'verbose_name': '上传文件历史表', 'verbose_name_plural': '上传文件历史表'},
        ),
    ]
