# Generated by Django 2.2.7 on 2020-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_auto_20200523_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('name', models.CharField(max_length=128, verbose_name='反馈分类')),
                ('desc', models.CharField(max_length=512, null=True, verbose_name='反馈简介')),
                ('author_id', models.IntegerField(db_index=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '反馈类别表',
                'verbose_name_plural': '反馈类别表',
                'ordering': ('-created_time',),
                'unique_together': {('name', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('name', models.CharField(max_length=128, verbose_name='反馈标题')),
                ('category_id', models.IntegerField(db_index=True, default=1, verbose_name='反馈类别')),
                ('desc', models.TextField(verbose_name='反馈内容')),
                ('author_id', models.IntegerField(db_index=True, verbose_name='创建人')),
                ('reply', models.CharField(max_length=256, null=True, verbose_name='回复内容')),
                ('reply_author_id', models.IntegerField(db_index=True, null=True, verbose_name='回复人id')),
            ],
            options={
                'verbose_name': '意见反馈表',
                'verbose_name_plural': '意见反馈表',
                'ordering': ('-created_time',),
                'unique_together': {('name', 'is_active')},
            },
        ),
    ]
