# Generated by Django 2.2.7 on 2020-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_feedback_feedbackcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='desc',
            field=models.CharField(max_length=1024, verbose_name='反馈内容'),
        ),
    ]
