# Generated by Django 2.2.7 on 2020-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0006_auto_20200602_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact_way',
            field=models.CharField(default=123, max_length=30, verbose_name='联系方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='反馈标题'),
        ),
    ]
