# Generated by Django 2.2.7 on 2020-06-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_auto_20200603_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
