# Generated by Django 2.2.7 on 2020-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0008_remove_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcategory',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='顺序'),
            preserve_default=False,
        ),
    ]
