# Generated by Django 2.2.7 on 2020-06-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_feedbackcategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcategory',
            options={'ordering': ('order',), 'verbose_name': '反馈类别表', 'verbose_name_plural': '反馈类别表'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='desc',
            new_name='content',
        ),
        migrations.AddField(
            model_name='feedback',
            name='html_content',
            field=models.CharField(default=123, max_length=3000, verbose_name='反馈html内容'),
            preserve_default=False,
        ),
    ]
