# Generated by Django 2.2.7 on 2020-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_feedback_reply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistorymodel',
            name='url',
            field=models.URLField(verbose_name='上传地址'),
        ),
    ]
