# Generated by Django 2.2.14 on 2020-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0013_auto_20200612_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistorymodel',
            name='bucket',
            field=models.CharField(default='', max_length=64, verbose_name='桶'),
        ),
        migrations.AddField(
            model_name='uploadhistorymodel',
            name='file',
            field=models.CharField(default='', max_length=512, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='uploadhistorymodel',
            name='raw_file',
            field=models.CharField(default='', max_length=512, verbose_name='文件原名称'),
        ),
        migrations.AddField(
            model_name='uploadhistorymodel',
            name='size',
            field=models.FloatField(default=0.0, verbose_name='大小/kb为单位'),
        ),
        migrations.AlterField(
            model_name='uploadhistorymodel',
            name='url',
            field=models.URLField(verbose_name='上传地址'),
        ),
    ]
