# Generated by Django 2.2.7 on 2019-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('category_id', models.PositiveSmallIntegerField(db_index=True, verbose_name='收藏类别id')),
                ('resource_id', models.PositiveSmallIntegerField(db_index=True, verbose_name='资源id')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '帖子')], db_index=True, verbose_name='资源类型')),
            ],
            options={
                'verbose_name': '用户收藏资源详情表',
                'verbose_name_plural': '用户收藏资源详情表',
                'ordering': ('-update_time', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='CollectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('user_id', models.PositiveIntegerField(db_index=True, verbose_name='用户id')),
                ('name', models.CharField(max_length=128, verbose_name='收藏类别名称')),
                ('desc', models.CharField(max_length=512, verbose_name='收藏类别描述')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('resource_num', models.PositiveIntegerField(default=0, verbose_name='收藏资源数量')),
            ],
            options={
                'verbose_name': '用户收藏帖子类别表',
                'verbose_name_plural': '用户收藏帖子类别表',
                'ordering': ('-update_time', '-created_time'),
            },
        ),
    ]
