# Generated by Django 2.2.7 on 2019-12-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('user_id', models.PositiveIntegerField(db_index=True, verbose_name='用户')),
                ('resource_id', models.PositiveSmallIntegerField(db_index=True, verbose_name='资源id')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '帖子')], db_index=True, verbose_name='点赞资源类型')),
            ],
            options={
                'verbose_name': '用户点赞表',
                'verbose_name_plural': '用户点赞表',
                'ordering': ('-update_time', '-created_time'),
            },
        ),
    ]
