# Generated by Django 2.2.7 on 2019-12-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0002_praise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('user_id', models.PositiveIntegerField(db_index=True, verbose_name='用户')),
                ('focus_id', models.PositiveIntegerField(db_index=True, verbose_name='关注人')),
            ],
            options={
                'verbose_name': '用户关注表',
                'verbose_name_plural': '用户关注表',
                'ordering': ('-update_time', '-created_time'),
            },
        ),
    ]
