# Generated by Django 2.2.7 on 2019-12-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0003_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='user_id',
            field=models.PositiveIntegerField(db_index=True, default=21, verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
