# Generated by Django 2.2.14 on 2020-09-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0007_auto_20200828_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praise',
            name='type',
        ),
        migrations.AddField(
            model_name='praise',
            name='t',
            field=models.PositiveSmallIntegerField(choices=[(1, '文章'), (2, '回复')], default=1, verbose_name='资源类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='praise',
            name='praise_or_trample',
            field=models.SmallIntegerField(choices=[(-1, 'cai'), (1, 'zan')], verbose_name='赞或踩'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='resource_id',
            field=models.IntegerField(db_index=True, verbose_name='资源id'),
        ),
    ]
