# Generated by Django 2.2.14 on 2020-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0008_auto_20200903_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='praise_or_trample',
            field=models.SmallIntegerField(choices=[(-1, 'cai'), (1, 'zan')], default=1, verbose_name='赞或踩'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='t',
            field=models.PositiveSmallIntegerField(choices=[(1, '文章'), (2, '回复')], db_index=True, verbose_name='资源类型'),
        ),
    ]
