# Generated by Django 2.2.14 on 2020-10-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0009_auto_20200929_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='praise',
            unique_together={('user_id', 'resource_id', 't')},
        ),
    ]
