# Generated by Django 2.2.14 on 2020-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0011_auto_20201024_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('user_id', models.PositiveIntegerField(db_index=True, verbose_name='用户')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, '用户注册'), (2, '用户登录'), (3, '用户发布文章/提问'), (4, '用户更新文章/提问'), (5, '用户评论'), (6, '用户点赞')], db_index=True, default=0, verbose_name='用户动作')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='操作ip')),
                ('resource_id', models.IntegerField(default=0, verbose_name='操作资源id')),
                ('extra_type', models.SmallIntegerField(default=0, verbose_name='额外类型')),
                ('extra_data', models.TextField(default='', verbose_name='其它信息')),
            ],
            options={
                'verbose_name': '用户动态表',
                'verbose_name_plural': '用户动态表',
            },
        ),
        migrations.RemoveField(
            model_name='praise',
            name='is_active',
        ),
    ]
