# Generated by Django 2.2.14 on 2020-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0013_auto_20201031_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='用户'),
        ),
    ]
