# Generated by Django 2.2.14 on 2020-11-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0014_auto_20201031_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdynamic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userdynamic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
