# Generated by Django 2.2.14 on 2020-10-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255, verbose_name='应用名称')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(db_index=True, max_length=255)),
                ('image', models.URLField(verbose_name='图片icon')),
                ('redirect_uri', models.URLField(verbose_name='回调uri')),
                ('access_token_uri', models.URLField(verbose_name='access token uri')),
                ('info_uri', models.URLField(verbose_name='用户信息uri')),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'app',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserOAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('extra_data', django_extensions.db.fields.json.JSONField(default=dict, verbose_name='额外内容')),
                ('uid', models.BigIntegerField(verbose_name='第三方用户id')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_oauth', to='oauth.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_oauth',
                'verbose_name_plural': 'user_oauth',
                'ordering': ('-created_time',),
            },
        ),
    ]
