# Generated by Django 2.2.14 on 2020-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_url',
            field=models.URLField(default=None, verbose_name='应用url'),
            preserve_default=False,
        ),
    ]
