# Generated by Django 2.2.14 on 2020-10-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_application_app_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='access_token_uri',
        ),
        migrations.RemoveField(
            model_name='application',
            name='app_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='info_uri',
        ),
        migrations.RemoveField(
            model_name='application',
            name='redirect_uri',
        ),
        migrations.AddField(
            model_name='application',
            name='load_modules',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='application',
            name='scope',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useroauth',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth', to=settings.AUTH_USER_MODEL),
        ),
    ]
