# Generated by Django 2.2.14 on 2020-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20201013_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='redirect_uri',
            field=models.URLField(default='', verbose_name='回调uri'),
        ),
    ]
