# Generated by Django 2.2.14 on 2020-10-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_application_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='help_text',
            field=models.CharField(default='', max_length=64, verbose_name='图片提示文字'),
        ),
    ]
