# Generated by Django 2.2.14 on 2020-10-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_application_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroauth',
            name='home_url',
            field=models.URLField(null=True, verbose_name='用户个人首页'),
        ),
    ]
