# Generated by Django 2.2.14 on 2020-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_useroauth_home_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='chinese_app_name',
            field=models.CharField(default='', max_length=255, verbose_name='应用中文名称'),
        ),
    ]
